before_script:
# Updates image to be able to launch scripts-common-tests.
  - export SCRIPTS_COMMON_PATH="$PWD/utilities.sh"
  - ln -s /usr/local/bin/bash /bin/bash
# Installs required dependency, including procps and locale which are not available in Bash Docker image.
  - echo "Installing git, procps, locale"
  - export MUSL_LOCPATH=/usr/local/share/i18n/locales/musl
  - apk update && apk upgrade && apk add --no-cache git procps cmake make musl-dev gcc gettext-dev libintl
  - cd ..
  - git clone https://gitlab.com/rilian-la-te/musl-locales.git
  - cd musl-locales && cmake . && make && make install && cd ..
# Retrieves dedicated scripts-common tests project.
  - echo "Retrieving tests project"
  - git clone https://$CI_READ_TOKEN@gitlab.com/bertrand-benoit/scripts-common-tests.git --recursive

# Usually GNU/Bash 5.0+ is available on modern GNU/Linux OS.
v5.0-gnu-bash:
  stage: test
  image: bash:5.0
  script:
    - echo "Testing scripts-common with GNU/Bash version 5.0+ (target => modern GNU/Linux OS)"
    - BSC_TESTS_RUNASROOT=1 scripts-common-tests/tests.sh

v4.0-gnu-bash:
  stage: test
  image: bash:4.0
  script:
    - echo "Testing scripts-common with GNU/Bash version 4.0+"
    - BSC_TESTS_RUNASROOT=1 scripts-common-tests/tests.sh

# Only GNU/Bash 3.2+ seems available on some MacOS OS.
v3.2-gnu-bash:
  stage: test
  image: bash:3.2
  script:
    - echo "Testing scripts-common with GNU/Bash version 3.2+ (target => some MacOS version)"
    - BSC_TESTS_RUNASROOT=1 scripts-common-tests/tests.sh
